tiers:
  interactive:
    max_fractal_iter: 300
    mfs_q: 7
    wavelet_bands: 4
    planner_rollouts: 64
    planner_depth: 6
    sbert_backend: "gpu"
    graph_batch_ms: 10
  standard:
    max_fractal_iter: 500
    mfs_q: 11
    wavelet_bands: 6
    planner_rollouts: 128
    planner_depth: 8
    sbert_backend: "cpu"
    graph_batch_ms: 20
  deep:
    max_fractal_iter: 1000
    mfs_q: 15
    wavelet_bands: 8
    planner_rollouts: 256
    planner_depth: 12
    sbert_backend: "cpu"
    graph_batch_ms: 50
